 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 jobs:
   build:
     docker:
       - image: microsoft/dotnet:sdk
     environment:
       DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
       DOTNET_CLI_TELEMETRY_OPTOUT: 1
     
     steps:
       - checkout
       - run: dotnet restore
       - run: dotnet build
       - run: dotnet run
      
 workflows:
  version: 2
  workflow:
    jobs:
    - build
#language: csharp
#dist: trusty
#mono: none
#dotnet: 2.0.0
#script:
#  - dotnet restore
#  - dotnet build
