#Comment to trigger a fresh commit
 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 jobs:
   build:
     docker: 
       - image: cimg/python:3.7
     
     steps:
       - checkout
#       - run: conda create --name brian_builder python=3.7 -y
#       - run: 
#           name: Initialize conda
#           command: conda init powershell
#       - run: 
#           name: Create 'brian_builder' conda environment
#           command: conda create --name brian_builder python=3.7 -y
       - restore_cache:  # ensure this step occurs *before* installing dependencies
           key: v1-dependencies-{% raw %}{{ checksum "features/requirements.txt" }}{% endraw %}
       - run:
           name: Install dependencies
           command: |
             conda activate brian_builder
             pip install -r features/requirements.txt
             easy_install behave
       - save_cache:
          key: v1-dependencies-{% raw %}{{ checksum "features/requirements.txt" }}{% endraw %}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.7/site-packages"
       - run: mkdir test-results
       - store_test_results:
           path: test-results

 workflows:
  version: 2
  workflow:
    jobs:
    - build
