#Comment to trigger a fresh commit
 version: 2.1

 jobs:
   build:
     docker: 
       - image: continuumio/anaconda3
     
     steps:
       - checkout
       - run: conda create --name kedro-environment python=3.7 -y
       - run: 
           name: Initialize conda
           command: conda init bash && activate kedro-environment
       - run: 
           name: Install virtualenv dependancy for conda environment
           command: conda install -y virtualenv
       - restore_cache:  # ensure this step occurs *before* installing dependencies
           key: v4-dependencies-{{ checksum "features/requirements.txt" }}
#       - run: pip install --user cffi==1.10.0
#       - run:
#           name: Install dependencies
#           command: |
#             pip install -r features/requirements.txt
       - save_cache:
          key: v4-dependencies-{{ checksum "features/requirements.txt" }}
          paths:
            - ".venv"
#       - run: source env/kedro-environment/bin/activate
       - run: pip install pipenv jmespath dynaconf cachetools toposort anyconfig kedro
       - run: mkdir kedro-environment && cd kedro-environment
#       - run: python -m pytest -m 'not integration ' -n 3 src/
       - run:
           name: Run tests
           command: |
             set -e
             TEST_FILES=$(circleci tests glob "src/tests/*.py" | circleci tests split --split-by=timings)
             mkdir -p test-results
             pytest --verbose --junitxml=test-results/junit.xml $TEST_FILES
       - run: mkdir test-results
       - store_test_results:
           path: test-results

 workflows:
  version: 2
  workflow:
    jobs:
    - build
