 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 jobs:
   build:
     executor:
       name: win/default
     steps:
       - checkout
       - run: dotnet restore
       - run: dotnet build

 workflows:
  version: 2
  workflow:
    jobs:
    - build
#language: csharp
#dist: trusty
#mono: none
#dotnet: 2.0.0
#script:
#  - dotnet restore
#  - dotnet build
